/* AUTO-GENERATED by server/audit-assets.ps1 - do not edit by hand.
   Slugs whose assets were unreachable at audit time. The feed hides
   these until the assets are back (re-run the audit). */
window.B0_ASSETS_MISSING = [];
