/* ============================================================
   0xB0 GAMES — homepage + shared site logic
   (grid rendering, search, category filters, random game,
    3D tilt, 3D hero showcase, scroll reveals,
    tab disguise + panic via the settings engine)
   ============================================================ */
/*global ALL_GAMES, findGame, gameCategories, gameHref, tileInnerHTML, B0Settings*/

(function () {
  'use strict';

  /* ---------------- asset gate --------------------------------- */
  /* A game only shows in the feed while its assets are on hand.
     js/assets-status.js (auto-generated by server/audit-assets.ps1)
     declares the slugs whose assets could not be reached at audit
     time — those tiles stay hidden until the assets come back (just
     re-run the audit, the feed updates). A missing manifest means
     "no gate" and everything shows, so nothing can ever be wiped
     out by a stale file. */
  var assetBlock = {};
  try {
    if (typeof window.B0_ASSETS_MISSING !== 'undefined' &&
        window.B0_ASSETS_MISSING && window.B0_ASSETS_MISSING.length) {
      for (var bi = 0; bi < window.B0_ASSETS_MISSING.length; bi++) {
        if (window.B0_ASSETS_MISSING[bi]) assetBlock[window.B0_ASSETS_MISSING[bi]] = 1;
      }
    }
  } catch (err) { assetBlock = {}; }

  function hasAssets(g) {
    return !assetBlock[g.slug];
  }

  /* ---------------- tiny helpers ------------------------------ */

  /* HTML-escape anything that lands inside an attribute or text node. */
  function esc(str) {
    return String(str == null ? '' : str)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#39;');
  }

  function $(id) { return document.getElementById(id); }

  /* ---------------- Tab disguise button ------------------------ */

  var cloakBtn = $('cloakBtn');

  function refreshCloakBtn() {
    if (!cloakBtn) return;
    var disguised = B0Settings.get().profile !== 'off';
    cloakBtn.classList.toggle('on', disguised);
    cloakBtn.title = disguised
      ? 'Disguise is ON — click to show 0xB0 again'
      : 'Disguise this tab as something boring (Google Docs, Canvas…)';
  }

  if (cloakBtn) {
    cloakBtn.addEventListener('click', function () {
      B0Settings.toggleDisguise();
      refreshCloakBtn();
    });
    refreshCloakBtn();
  }

  /* ---------------- Panic button (key is handled by settings.js) */

  var panicBtn = $('panicBtn');
  if (panicBtn) {
    panicBtn.addEventListener('click', function () {
      B0Settings.panic();
    });
  }

  /* ---------------- Mobile nav -------------------------------- */

  var navToggle = $('navToggle');
  var navLinks = $('navLinks');
  if (navToggle && navLinks) {
    navToggle.addEventListener('click', function () {
      navLinks.classList.toggle('open');
    });
  }

  /* Close the nav dropdown when clicking outside of it, and after
     picking an item (otherwise <details> stays open on mobile). */
  var navDrop = $('navDrop');
  if (navDrop) {
    document.addEventListener('click', function (e) {
      if (navDrop.open && !navDrop.contains(e.target)) navDrop.open = false;
    });
    navDrop.addEventListener('click', function (e) {
      if (e.target.closest('a')) navDrop.open = false;
    });
  }

  /* ---------------- Random game ------------------------------- */

  var randomBtn = $('randomBtn');
  if (randomBtn) {
    randomBtn.addEventListener('click', function () {
      if (typeof ALL_GAMES === 'undefined' || !ALL_GAMES.length) return;
      location.href = gameHref(ALL_GAMES[~~(Math.random() * ALL_GAMES.length)]);
    });
  }

  /* ---------------- Login state in nav ---------------------------- */

  var loginSlot = $('loginSlot');
  if (loginSlot) {
    try {
      var authUser = window.B0Auth ? B0Auth.getCurrentUser() : null;
      if (authUser) {
        var badge = '';
        if (authUser.role === 'admin') {
          badge += '<span class="nav-role" title="Site owner">⚡</span>';
        }
        if (window.B0Auth && B0Auth.titleInfo) {
          var t = B0Auth.titleInfo(authUser.title);
          var tip = t.label + ' — cosmetic title, assigned by the site owner';
          badge += '<span class="nav-role nav-title" title="' + esc(tip) +
            '" style="color:' + esc(t.color) + '">' + t.emoji + '</span>';
        }
        loginSlot.innerHTML =
          '<a href="login.html" class="nav-link-user" title="Logged in as ' + esc(authUser.username) + '">' +
          '<span class="nav-avatar">' + (authUser.avatar || '👤') + '</span>' +
          '<span class="nav-username">' + esc(authUser.username) + '</span>' +
          badge +
          '</a>';
      } else {
        loginSlot.innerHTML = '<a href="login.html" title="Sign up or log in">👤 Login</a>';
      }
    } catch (err) {
      loginSlot.innerHTML = '<a href="login.html">👤 Login</a>';
    }
  }

  if (window.matchMedia('(hover: hover)').matches) {
    var tiltCard = null;
    document.addEventListener('mousemove', function (e) {
      var card = e.target && e.target.closest ? e.target.closest('.card, .profile-card') : null;
      if (tiltCard && tiltCard !== card) {
        tiltCard.style.transform = '';
        tiltCard = null;
      }
      if (!card) return;
      tiltCard = card;
      var r = card.getBoundingClientRect();
      var x = (e.clientX - r.left) / r.width - 0.5;
      var y = (e.clientY - r.top) / r.height - 0.5;
      card.style.transform =
        'perspective(700px) rotateX(' + (-y * 6).toFixed(2) + 'deg) rotateY(' +
        (x * 8).toFixed(2) + 'deg) translateY(-4px) scale(1.02)';
    });
  }

  /* ---------------- 3D hero showcase (homepage) ---------------- */

  var heroStage = $('heroStage');
  var scInner = $('scInner');
  if (heroStage && scInner && typeof ALL_GAMES !== 'undefined') {
    var seenS = {};
    var showcase = [];
    /* Hot games with real artwork first, then anything else with art. */
    ALL_GAMES.forEach(function (g) {
      if (g.thumb && g.badge === 'Hot' && hasAssets(g) && !seenS[g.slug] && showcase.length < 5) {
        seenS[g.slug] = 1;
        showcase.push(g);
      }
    });
    ALL_GAMES.forEach(function (g) {
      if (g.thumb && hasAssets(g) && !seenS[g.slug] && showcase.length < 5) {
        seenS[g.slug] = 1;
        showcase.push(g);
      }
    });

    if (showcase.length >= 3) {
      scInner.innerHTML = showcase.map(function (g, i) {
        return (
          '<div class="sc-slot" style="--i:' + i + '">' +
          '<a class="sc-card" href="' + gameHref(g) + '" title="Play ' + esc(g.title) + '">' +
          '<img src="' + esc(g.thumb) + '" alt="' + esc(g.title) + '" loading="lazy"/>' +
          '<span>' + esc(g.title) + '</span>' +
          '</a></div>'
        );
      }).join('');

      /* the whole stage subtly rotates toward the cursor */
      if (window.matchMedia('(hover: hover)').matches) {
        document.addEventListener('mousemove', function (e) {
          var rx = (e.clientY / window.innerHeight - 0.5) * -7;
          var ry = (e.clientX / window.innerWidth - 0.5) * 9;
          scInner.style.transform = 'rotateX(' + rx.toFixed(2) + 'deg) rotateY(' + ry.toFixed(2) + 'deg)';
        });
      }
    } else {
      heroStage.style.display = 'none';
    }
  }

  /* ---------------- scroll reveal ------------------------------- */
  /* Reveal SMALL elements only. Never tag giant containers like the
     games .section (it can be ~28,000px tall — a 6% visibility
     threshold can never be met inside a normal viewport, which once
     left the whole grid invisible). threshold: 0 reveals the moment
     any pixel enters the viewport. */

  if ('IntersectionObserver' in window) {
    var io = new IntersectionObserver(function (entries) {
      entries.forEach(function (en) {
        if (en.isIntersecting) {
          en.target.classList.add('revealed');
          io.unobserve(en.target);
        }
      });
    }, { threshold: 0 });

    var revealTargets = document.querySelectorAll(
      '.unbanner, .section-head, .chips, .feature, .play-info, .info-card'
    );
    for (var ri = 0; ri < revealTargets.length; ri++) {
      revealTargets[ri].classList.add('reveal');
      io.observe(revealTargets[ri]);
    }

    /* safety net — nothing may ever stay invisible:
       after 2s, force-reveal anything still hidden that is in
       (or near) the viewport. Deep content still animates on scroll. */
    setTimeout(function () {
      var hidden = document.querySelectorAll('.reveal:not(.revealed)');
      for (var hi = 0; hi < hidden.length; hi++) {
        var r = hidden[hi].getBoundingClientRect();
        if (r.top < window.innerHeight * 2) {
          hidden[hi].classList.add('revealed');
        }
      }
    }, 2000);
  }

  /* ---------------- boss mode + grid density ------------------- */
  try {
    var sitePrefs = B0Settings.get();
    if (sitePrefs.gridDensity === 'compact') {
      document.body.classList.add('grid-compact');
    }
    if (sitePrefs.bossMode) {
      var bossOverlay = document.createElement('div');
      bossOverlay.className = 'boss-overlay';
      bossOverlay.innerHTML =
        '<div class="boss-inner"><div class="boss-eye">👁️</div>' +
        '<p>Paused.</p><p class="boss-sub">Move your mouse or click to continue</p></div>';
      document.body.appendChild(bossOverlay);
      var bossHide = function () { bossOverlay.classList.remove('show'); };
      bossOverlay.addEventListener('mousemove', bossHide);
      bossOverlay.addEventListener('click', bossHide);
      window.addEventListener('focus', bossHide);
      document.addEventListener('keydown', bossHide);
      window.addEventListener('blur', function () { bossOverlay.classList.add('show'); });
    }
  } catch (err) {}

  /* ---------------- Homepage grid ----------------------------- */

  var grid = $('grid');
  if (!grid) return; /* not the homepage */

  /* games whose assets are on hand right now — the feed, its counters
     and the search results all respect the asset gate. */
  var availableTotal = 0;
  for (var at = 0; at < ALL_GAMES.length; at++) {
    if (hasAssets(ALL_GAMES[at])) availableTotal++;
  }

  var chipsEl = $('chips');
  var searchInput = $('searchInput');
  var searchClear = $('searchClear');
  var countEl = $('gameCount');
  var railEl = $('popularRail');

  var activeCat = 'All';
  var query = '';

  /* ---------- hero stat counters (no more "9 games" flash) --- */

  var statGames = $('statGames');
  if (statGames && typeof ALL_GAMES !== 'undefined') statGames.textContent = availableTotal;

  var statLocal = $('statLocal');
  if (statLocal && typeof ALL_GAMES !== 'undefined') {
    statLocal.textContent = ALL_GAMES.filter(function (g) { return !g.external && hasAssets(g); }).length;
  }

  /* ---------- popular rail: the "Hot" games ------------------- */

  function renderRail() {
    if (!railEl || typeof ALL_GAMES === 'undefined') return;
    var seen = {};
    var picks = [];
    ALL_GAMES.forEach(function (g) {
      if (picks.length >= 14) return;
      if (seen[g.slug] || g.badge !== 'Hot' || !hasAssets(g)) return;
      seen[g.slug] = 1;
      picks.push(g);
    });
    /* never ship an empty section — top up with local originals */
    if (picks.length < 8) {
      ALL_GAMES.forEach(function (g) {
        if (picks.length >= 14) return;
        if (seen[g.slug] || !hasAssets(g)) return;
        seen[g.slug] = 1;
        picks.push(g);
      });
    }
    if (!picks.length) {
      var sec = railEl.closest ? railEl.closest('.section') : null;
      if (sec) sec.style.display = 'none';
      return;
    }
    railEl.innerHTML = picks.map(function (g, i) { return cardHTML(g, i); }).join('');
  }

  /* ---------- one card, used by both the grid and the rail ----- */

  function cardHTML(g, i) {
    var badge = g.badge ? '<span class="flag">' + esc(g.badge) + '</span>' : '';
    var newTab = '';
    try { if (B0Settings.get().newTab) newTab = ' target="_blank" rel="noopener"'; } catch (err) {}
    /* category slug for per-category accent tinting + stagger index for
       the cascade entrance (capped so the last card waits <= ~1s) */
    var catCls = (g.category || 'other').toLowerCase()
      .replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') || 'other';
    var n = Math.min(i || 0, 36);
    return (
      '<a class="card" data-cat="' + esc(catCls) + '" style="--n:' + n +
      '" href="' + gameHref(g) + '"' + newTab +
      ' title="Play ' + esc(g.title) + '">' +
      '<div class="thumb">' +
      badge +
      tileInnerHTML(g) +
      '<div class="play-badge"><div class="circle">' +
      '<svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor"><path d="M8 5v14l11-7z"/></svg>' +
      '</div></div>' +
      '</div>' +
      '<div class="meta"><span class="t">' + esc(g.title) + '</span>' +
      '<span class="cat">' + esc(g.category) + '</span></div>' +
      '</a>'
    );
  }

  /* ---------- filter + render ---------------------------------- */

  function haystack(g) {
    /* pre-built once per game; searching 544 titles on every keystroke
       used to rebuild this string 544 times. */
    if (g._hay === undefined) {
      g._hay = (g.title + ' ' + g.category + ' ' + (g.description || '')).toLowerCase();
    }
    return g._hay;
  }

  function matches(g) {
    if (activeCat !== 'All' && g.category !== activeCat) return false;
    var q = query.trim().toLowerCase();
    if (!q) return true;
    /* every word must appear somewhere, so "snake io" narrows down */
    var hay = haystack(g);
    var words = q.split(/\s+/);
    for (var i = 0; i < words.length; i++) {
      if (words[i] && hay.indexOf(words[i]) === -1) return false;
    }
    return true;
  }

  function render() {
    var shown = [];
    for (var i = 0; i < ALL_GAMES.length; i++) {
      if (matches(ALL_GAMES[i]) && hasAssets(ALL_GAMES[i])) shown.push(ALL_GAMES[i]);
    }

    grid.innerHTML = shown.length
      ? shown.map(function (g, i) { return cardHTML(g, i); }).join('')
      : '<div class="empty-note">No games match — try another search 👀' +
        '<br><a class="empty-request" href="https://github.com/va1uxxx/0xB0-Games/issues/new?labels=Game%20Request&title=Game%20Request%3A%20&body=**Game%20name%3A**%0A**Link%20to%20the%20game%3A**%0A**Category%3A**%0A**Why%20should%200xB0%20add%20it%3F**" target="_blank" rel="noopener">Request this game on GitHub →</a>' +
        '</div>';

    if (countEl) {
      countEl.textContent = shown.length === availableTotal
        ? shown.length + ' games'
        : shown.length + ' of ' + availableTotal + ' games';
    }
  }

  /* ---------- category chips ---------------------------------- */

  if (chipsEl) {
    var cats = ['All'].concat(gameCategories());
    chipsEl.innerHTML = cats
      .map(function (c) {
        return '<button class="chip' + (c === 'All' ? ' on' : '') +
          '" data-cat="' + esc(c) + '">' + esc(c) + '</button>';
      })
      .join('');

    chipsEl.addEventListener('click', function (e) {
      var btn = e.target.closest ? e.target.closest('.chip') : null;
      if (!btn) return;
      activeCat = btn.getAttribute('data-cat');
      var all = chipsEl.querySelectorAll('.chip');
      for (var i = 0; i < all.length; i++) all[i].classList.toggle('on', all[i] === btn);
      render();
    });
  }

  /* ---------- search box --------------------------------------- */

  function refreshClearBtn() {
    if (searchClear) searchClear.hidden = !searchInput || !searchInput.value;
  }

  if (searchInput) {
    var debounce = null;

    function onQueryChange() {
      if (debounce) clearTimeout(debounce);
      /* 544 cards of HTML per keystroke is janky on a Chromebook —
         wait until the typing pauses. */
      debounce = setTimeout(function () {
        query = searchInput.value;
        refreshClearBtn();
        render();
      }, 90);
    }

    searchInput.addEventListener('input', onQueryChange);

    searchInput.addEventListener('keydown', function (e) {
      if (e.key === 'Escape') {
        e.stopPropagation();
        if (searchInput.value) {
          searchInput.value = '';
          query = '';
          refreshClearBtn();
          render();
        } else {
          searchInput.blur();
        }
      }
    });

    if (searchClear) {
      searchClear.addEventListener('click', function () {
        searchInput.value = '';
        query = '';
        refreshClearBtn();
        render();
        searchInput.focus();
      });
    }

    /* "/" focuses search from anywhere (unless you're already typing) */
    document.addEventListener('keydown', function (e) {
      if (e.key !== '/' || e.ctrlKey || e.metaKey || e.altKey) return;
      var t = e.target;
      if (t && (t.isContentEditable ||
          /^(input|textarea|select)$/i.test(t.tagName || ''))) return;
      e.preventDefault();
      searchInput.focus();
      searchInput.select();
    });

    refreshClearBtn();
  }

  /* ---------- deep link: index.html?search=snake ---------------- */

  try {
    var pre = new URLSearchParams(location.search).get('search');
    if (pre && searchInput) {
      searchInput.value = pre;
      query = pre;
      refreshClearBtn();
    }
    var preCat = new URLSearchParams(location.search).get('cat');
    if (preCat && chipsEl) {
      var btn = chipsEl.querySelector('.chip[data-cat="' + preCat.replace(/"/g, '') + '"]');
      if (btn) btn.click();
    }
  } catch (err) {}

  renderRail();
  render();
})();
